### ISSUE TITLE
rn-jsbridge使用方式的问题

### ISSUE THREAD

**Issue by guojiabin** [chenzhaolong/ird-jsBridge#9]
你写的使用方式根本就不行啊  在RN 端yarn add ird-jsBridge  import RnBridge from 'ird-RnBridge'后; 只能使用RnBridge.switchMode({mode: 'rn'})这个函数  别的api找不到例如（RnBridge.initWebview(webview, {
    method(params, send) {}
})等等方法找不到），我想问一下  您如何使用的呢？

**Comment by chenzhaolong** [comment]
你的安装方式出错了，应该是npm i ird-rnbridge，ird-jsBridge只是一个项目名，没有发布到npm，详情可以看一下https://github.com/chenzhaolong/ird-jsBridge/tree/master/ird-RnBridge
